name: flutter_config_switcher
description: A command-line tool to switch between different configurations in a Flutter project.
version: 0.0.2
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  args: ^2.3.1
  cli_util: ^0.4.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  mason_logger: ^0.2.0
  path: ^1.8.2
  pub_updater: ^0.3.1

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0+1

executables:
  ? flutter_config_switcher
