name: flutter_config_switcher
description: A Very Good Project created by Very Good CLI.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  args: ^2.3.1
  cli_util: ^0.3.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  mason_logger: ^0.2.0
  path: ^1.8.3
  pub_updater: ^0.2.1

dev_dependencies:
  flutter_launcher_icons: "^0.11.0"
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0

executables:
  flutter_config_switcher:
